import {Town} from './town';

export const MOCKTOWNS: Town[] = [
	{ name: "Phlueggerville"},
	{ name: "Testaria"},
	{ name: "Lucaria"},
	{ name: "Via Novus"},
	{ name: "Effoulle"},
	{ name: "Gaspar"},
	{ name: "Melchoir"},
	{ name: "Balthasar"},
	{ name: "Herod"},
	{ name: "Pilote"},
	{ name: "Ezio"},
	{name: "Adso"},
	{name: "Ambrosio"},
	{name: "Felipe"},
	{name: "Ruthville"},
	{name: "Gridania"},
	{name: "Limsa"},
	{name: "Uldah"},
	{name: "Mysidia"},
	{name: "Fynne"},
	{name: "Corneria"},
	{name: "Savonia"},
	{name: "Pravoka"},
	{name: "Salamanda"},
	{name: "Baron"},
	{name: "Tuft"},
	{name: "Narshe"},
	{name: "Mog"},
	{name: "Yeti"},
	{name: "Macintosh"},
	{name: "Starbuck"},
	{name: "Amos"}
];